
### Opret en bruger med en user rolle
POST https://bicycle.thegreenway.dk/api/auth/register/
Content-Type: application/json

{
    "username": "Lars",
    "password": "green123"
}

### Login og gem token
POST https://bicycle.thegreenway.dk/api/auth/login
Content-Type: application/json

{
  "username": "Nicolai",
  "password": "green123"
}

### Tilføj en admin rolle til brugeren
### Kopier den jwt-token som du får ud ved at logge brugeren ind og sæt den ind under Authorization
### På den måde er det muligt at tilføje roller

POST https://bicycle.thegreenway.dk/api/auth/user/addrole/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsYXJzIiwic3ViIjoiUGV0ZXIiLCJleHAiOjE3MzM4MTI5NzIsInJvbGVzIjoidXNlciIsInVzZXJuYW1lIjoiUGV0ZXIifQ.yOSUcxH9iVBpk3XELPMBYj8thP9qOlbrINc3YxKCot8

{
    "role": "admin"
}

### Her fylder vi databasen med data
GET https://bicycle.thegreenway.dk/api/bicycles/populate
Content-Type: application/json

### Her henter vi alle bicycles
GET https://bicycle.thegreenway.dk/api/bicycles
Accept: application/json

### Her henter vi alle frames
GET https://bicycle.thegreenway.dk/api/frames
Accept: application/json

### Her henter vi alle gears
GET https://bicycle.thegreenway.dk/api/gears
Accept: application/json

### Her henter vi alle saddles
GET https://bicycle.thegreenway.dk/api/saddles
Accept: application/json

### Her henter vi alle wheels
GET https://bicycle.thegreenway.dk/api/wheels
Accept: application/json




